# Generated by Django 4.2.5 on 2023-09-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_purchased', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('Transport', 'Transport'), ('Food', 'Food'), ('Leisure', 'Leisure'), ('Electronics', 'Electronics'), ('House&Renovation', 'House&Renovation'), ('Cloths', 'Cloths')], max_length=20)),
            ],
        ),
    ]
